print("##############################")
print("#                            #")
print("#    Muhammad Raka Azwar     #")
print("#       2210817210012        #")
print("#                            #")
print("##############################")